export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';
export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const GET_SELECTED_PRODUCT = 'GET_SELECTED_PRODUCT';
export const REQUEST_SELECTED_PRODUCT = 'REQUEST_SELECTED_PRODUCT';
export const SELECTED_PRODUCT_FAIL = 'SELECTED_PRODUCT_FAIL';

export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST';
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS';
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET';

export const NEW_CATEGORY_REQUEST = 'NEW_CATEGORY_REQUEST';
export const NEW_CATEGORY_SUCCESS = 'NEW_CATEGORY_SUCCESS';
export const NEW_CATEGORY_FAIL = 'NEW_CATEGORY_FAIL';
export const NEW_CATEGORY_RESET = 'NEW_CATEGORY_RESET';

export const ALL_CATEGORY_REQUEST = 'ALL_CATEGORY_REQUEST';
export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS';
export const ALL_CATEGORY_FAIL = 'ALL_CATEGORY_FAIL';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';
export const DELETE_CATEGORY_RESET = 'DELETE_CATEGORY_RESET';

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';
export const UPDATE_CATEGORY_RESET = 'UPDATE_CATEGORY_RESET';

export const DETAILS_CATEGORY_REQUEST = 'DETAILS_CATEGORY_REQUEST';
export const DETAILS_CATEGORY_SUCCESS = 'DETAILS_CATEGORY_SUCCESS';
export const DETAILS_CATEGORY_FAIL = 'DETAILS_CATEGORY_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET';

export const SET_SNACKBAR = 'SET_SNACKBAR';
